@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 25 11:32:51 -0700 2025
REM SW Build 3605665 on Fri Aug  5 22:53:37 MDT 2022
REM
REM IP Build 3603185 on Sat Aug  6 04:07:44 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_Payload_extract_behav -key {Behavioral:sim_1:Functional:tb_Payload_extract} -tclbatch tb_Payload_extract.tcl -protoinst "protoinst_files/bd_e185.protoinst" -protoinst "protoinst_files/bd_21d4.protoinst" -view C:/Users/zheng/Dropbox/01_work/04_polar_radar/01_rfsoc/cir_sounder/cir_sounder.sim/tb_Payload_extract_behav.wcfg -log simulate.log"
call xsim  tb_Payload_extract_behav -key {Behavioral:sim_1:Functional:tb_Payload_extract} -tclbatch tb_Payload_extract.tcl -protoinst "protoinst_files/bd_e185.protoinst" -protoinst "protoinst_files/bd_21d4.protoinst" -view C:/Users/zheng/Dropbox/01_work/04_polar_radar/01_rfsoc/cir_sounder/cir_sounder.sim/tb_Payload_extract_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
